# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 534)
        MainWindow.setMinimumSize(QtCore.QSize(950, 534))
        MainWindow.setMaximumSize(QtCore.QSize(950, 534))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo_10.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Choix_trad = QtWidgets.QComboBox(self.centralwidget)
        self.Choix_trad.setEnabled(True)
        self.Choix_trad.setGeometry(QtCore.QRect(680, 130, 161, 31))
        self.Choix_trad.setStyleSheet("QComboBox#Choix_trad {\n"
"    background-color: rgb(18, 39, 52,150);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(90, 186, 255);\n"
"    color: white;\n"
"    font: bold 12px;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 2px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox#Choix_trad::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QComboBox#Choix_trad QAbstractItemView {\n"
"    background-color: rgb(18, 39, 52);\n"
"    selection-background-color: rgb(29, 78, 109);\n"
"    border: 2px solid rgb(90, 186, 255);\n"
"}\n"
"\n"
"QComboBox#Choix_trad:hover {\n"
"    background-color: rgb(20, 54, 76,180);\n"
"}\n"
"\n"
"QComboBox#Choix_trad:pressed {\n"
"    background-color: rgb(29, 78, 109);\n"
"    border-style: inset;\n"
"}")
        self.Choix_trad.setMaxVisibleItems(10)
        self.Choix_trad.setObjectName("Choix_trad")
        self.selecte_path = QtWidgets.QPushButton(self.centralwidget)
        self.selecte_path.setGeometry(QtCore.QRect(170, 50, 200, 60))
        self.selecte_path.setStyleSheet(" QPushButton#selecte_path {\n"
"     \n"
"     background-color: rgb(18, 39, 52,180);\n"
"     border-style: outset;\n"
"     border-width: 3px;\n"
"     border-radius: 25px;\n"
"     border-color: rgb(90, 186, 255);\n"
"     color: white;\n"
"     font: bold 15px;\n"
"     min-width: 10px;\n"
"     padding: 5px;\n"
"    border-top-left-radius:2px;\n"
"     border-bottom-right-radius: 5px;\n"
" }\n"
" QPushButton#selecte_path:pressed {\n"
"     background-color: rgb(29, 78, 109);\n"
"     border-style: inset;\n"
" }\n"
"\n"
" QPushButton#selecte_path:hover {\n"
"    background-color: rgb(20, 54, 76,180);\n"
"}")
        self.selecte_path.setObjectName("selecte_path")
        self.Startinstall = QtWidgets.QPushButton(self.centralwidget)
        self.Startinstall.setGeometry(QtCore.QRect(580, 50, 200, 60))
        self.Startinstall.setStyleSheet("\n"
" QPushButton#Startinstall {\n"
"     \n"
"     background-color: rgb(18, 39, 52,180);\n"
"     border-style: outset;\n"
"     border-width: 3px;\n"
"     border-radius: 25px;\n"
"     border-color: rgb(90, 186, 255);\n"
"     color: white;\n"
"     font: bold 15px;\n"
"     min-width: 10px;\n"
"     padding: 5px;\n"
"    border-top-left-radius:2px;\n"
"     border-bottom-right-radius: 5px;\n"
" }\n"
" QPushButton#Startinstall:pressed {\n"
"     background-color: rgb(29, 78, 109);\n"
"     border-style: inset;\n"
" }\n"
"\n"
" QPushButton#Startinstall:hover {\n"
"    background-color: rgb(20, 54, 76,180);\n"
"}")
        self.Startinstall.setObjectName("Startinstall")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 445, 650, 41))
        self.label.setStyleSheet("\n"
"QLabel#label {\n"
"    background-color: rgb(18, 39, 52,180);\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"   /* border-color: rgb(90, 186, 255);*/\n"
"     border-color: rgb(90, 186, 255,80);\n"
"    color: white;\n"
"    font: normal 12px;  /* Police plus petite pour les messages */\n"
"    padding: 8px;\n"
"\n"
"\n"
"}\n"
"\n"
"QLabel#label:hover {\n"
"    background-color: rgb(20, 45, 60,180);\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 951, 511))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("back_950.jpg"))
        self.label_2.setObjectName("label_2")
        self.Choix_trad.raise_()
        self.label_2.raise_()
        self.selecte_path.raise_()
        self.Startinstall.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Installe traduction"))
        self.selecte_path.setText(_translate("MainWindow", "Choix Repertoire de SC"))
        self.Startinstall.setText(_translate("MainWindow", "Installe Traduction"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">texte</span></p></body></html>"))
